# Generated by Django 6.1.1 on 2026-10-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('backend', models.CharField(default='classical', max_length=20)),
                ('quality', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='IrisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('U', 'Unspecified')], default='U', max_length=1)),
                ('code', models.BinaryField()),
                ('mask', models.BinaryField()),
                ('shape', models.CharField(default='', max_length=20)),
                ('quality', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iris_templates', to='academics.student')),
            ],
        ),
    ]
